apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  type: NodePort
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
